# Generated by Django 4.0.6 on 2022-07-27 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=100)),
                ('Email', models.CharField(max_length=100)),
                ('AddressPostcode', models.CharField(max_length=100)),
                ('StateName', models.CharField(max_length=100)),
            ],
        ),
    ]
